apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poll
  template:
    metadata:
      labels:
        app: poll
    spec:
      containers:
      - name: poll
        image: epitechcontent/t-dop-600-poll:k8s
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128M"
        envFrom:
        - configMapRef:
            name: redis-config
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - poll
