apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgresql-data  # Use a subdirectory inside the mount point

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G      # Ensure this matches or exceeds the PV capacity
