apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  namespace: kube-public
  labels:
    app: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: http-proxy
      port: 80
      targetPort: 80
      nodePort: 30021
    - name: admin-dashboard
      port: 8080
      targetPort: 8080
      nodePort: 30042
